clientConfigs:
- login: test
  password: testpassword
- login: test2
  password: testpassword
- login: test3
  password: Y5Q7nLY_Bkkd_owP+RH+ow0jKcLDNwOu
- login: freebuild
  password: lu2MVrM7YyeFExR+IxeHM_zzsf1huFdP
port: 25701
